### ISSUE TITLE
Missing file extension

### ISSUE THREAD

**Issue by neosis** [minio/minio-jenkins#11]
Hi
While trying to upload a .deb file to minio server, file is getting uploaded without the extension.
Best
Ashutosh

**Comment by nitisht** [comment]
@neosis I have a fix and works while testing locally. Would it be possible for you to try this out and let us know if it works for you as well. We can then make a plugin release. You'll need to unzip the file first and then install the `.hpi` plugin file

[minio-storage.zip](https://github.com/minio/minio-jenkins/files/2108676/minio-storage.zip)

**Comment by nitisht** [comment]
Closing as fixed by https://github.com/jenkinsci/minio-storage-plugin/commit/af5ee3a3b3f33f7bdd2e54f3ab4befe1d0672cde . I see the extension is retained after upload in local testing. 

@neosis feel free to reopen if you see otherwise
