### ISSUE TITLE
Files uploaded to Minio server via Minio plugin should be zipped first

### ISSUE THREAD

**Issue by nitisht** [minio/minio-jenkins#4]
Jenkins build artifacts uploaded to Minio server via the Minio plugin should be uploaded as zipped files with a timestamp to differentiate between various files related to different builds. 

Otherwise it is difficult to identify files related to separate builds.

**Comment by kannappanr** [comment]
@nitisht Can you update the status of this issue?

**Comment by nitisht** [comment]
we can close this for now, may be take up later if there is interest from community
